application: 15thdoverscoutscdn
version: 1
runtime: python
api_version: 1

default_expiration: 7d

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js

- url: /.*
  static_files: index.html
  upload: index.html